export default {
  CREATE_EXERCISE: "CREATE_EXERCISE",
  UPDATE_EXERCISE: "UPDATE_EXERCISE",
  DELETE_EXERCISE: "DELETE_EXERCISE",
  LOAD_EXERCISES: "LOAD_EXERCISES",
  LOAD_USERS: "LOAD_USERS",
  ADD_USERS: "ADD_USERS",
};
